---
resources:
  - name: moneygr-repo
    type: git
    source:
      uri: https://github.com/maki-home/moneygr.git
      branch: master
  - name: cf
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space}}
      skip_cert_check: true
  - name: m2
    type: docker-image
    source:
      repository: making/home-m2
jobs:
  - name: moneygr-unit
    plan:
      - get: repo
        resource: moneygr-repo
        trigger: true
      - get: m2
      - task: unit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine
          inputs:
            - name: repo
            - name: m2
          run:
            path: sh
            args:
            - repo/ci/tasks/unit.sh
          params:
            _JAVA_OPTIONS: -Duser.timezone=Asia/Tokyo -Duser.language=ja -Duser.country=JP -Djava.security.egd=file:/dev/./urandom
  - name: moneygr-deploy
    plan:
      - get: repo
        resource: moneygr-repo
        trigger: true
        passed: [ moneygr-unit ]
      - get: m2
      - task: package
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine
          inputs:
            - name: repo
            - name: m2
          outputs:
            - name: output
          run:
            path: sh
            args:
            - repo/ci/tasks/package.sh
      - put: cf
        params:
          manifest: moneygr-repo/manifest.yml
          path: output/app.jar
          current_app_name: moneygr
